global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'Keletjo'
    static_configs:
      - targets: ['18.201.133.217:9100']